### ISSUE TITLE
TypeError when creating initial omapi instance

### ISSUE THREAD

**Issue by GitStoph** [CygnusNetworks/pypureomapi#30]
```
import pypureomapi

KEYNAME="defomapi"
KEY="wGYh1n9uC9Regws6n111zw=="

dhcp_server_ip="my.server.ip.address"
port = 7911 # Port of the omapi service

omapi = pypureomapi.Omapi(dhcp_server_ip, port, KEYNAME, KEY)
```
Yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 980, in __init__
    self.initialize_authenticator(newauth)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 1064, in initialize_authenticator
    response = self.query_server(msg)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 1053, in query_server
    self.send_message(message)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 1044, in send_message
    self.protocol.send_message(message, sign)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 944, in send_message
    message.sign(self.authenticators[self.defauth])
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 466, in sign
    self.signature = authenticator.sign(self.as_string(forsigning=True))
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 457, in as_string
    self.serialize(ret, forsigning)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 443, in serialize
    outbuffer.add_bindict(self.obj)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 212, in add_bindict
    self.add_net16string(key).add_net32string(value)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 183, in add_net32string
    return self.add_net32int(len(string)).add(string)
  File "/home/<myuser>/dhcpapi/venv/lib/python3.6/site-packages/pypureomapi.py", line 145, in add
    self.buff.write(data)
TypeError: a bytes-like object is required, not 'str'
```
Relevant portion of ISC-DHCP config:
```
key defomapi {
    algorithm hmac-md5;
    secret wGYh1n9uC9Regws6n111zw==;
};

omapi-key defomapi;
omapi-port 7911;
```
Python 3.6.7 on 18.04.2
Any ideas would be very welcome. Thank you!

**Comment by hgrohne-cygnusnetworks-de** [comment]
On Thu, Apr 04, 2019 at 08:50:05PM +0000, GitStoph wrote:
> KEYNAME="defomapi"
> KEY="wGYh1n9uC9Regws6n111zw=="

These are typed str.

> omapi = pypureomapi.Omapi(dhcp_server_ip, port, KEYNAME, KEY)

The documentation says that KEYNAME and KEY must be bytes (or None).

> TypeError: a bytes-like object is required, not 'str'

The error says the same. It could be moved much earlier by adding

    assert isinstance(user, bytes)
    assert isinstance(key, bytes)

to OmapiHMACMD5Authenticator.__init__.

Helmut

**Comment by cygnusb** [comment]
Thanks Helmut. In addition correct usage is:

```
KEYNAME=b"defomapi"
KEY=b"wGYh1n9uC9Regws6n111zw=="
...
omapi = pypureomapi.Omapi(dhcp_server_ip, port, KEYNAME, KEY)
```

Make sure to change your secret key now, after you posted it on Github to the world. :see_no_evil:

**Comment by GitStoph** [comment]
Apologies. I was attempting to encode via `.encode('utf-8') and using `b"key"`, and still having issues. My problem was that i was only doing the key, and not the keyname as well. I see the README has already been updated accordingly. Thanks very much for the quick and precise help, and for the great project!
